# Generated by Django 5.0.7 on 2024-10-10 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DupayAccount',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('account_type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability')], max_length=50)),
                ('account_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('phase_id', models.AutoField(primary_key=True, serialize=False)),
                ('phase_name', models.CharField(choices=[('committed', 'Committed'), ('pending_incoming', 'Pending Incoming'), ('pending_outgoing', 'Pending Outgoing')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DupayAsset',
            fields=[
                ('asset_id', models.AutoField(primary_key=True, serialize=False)),
                ('asset_name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='admin_transaction_processing.dupayaccount')),
            ],
        ),
        migrations.CreateModel(
            name='DupayDenomination',
            fields=[
                ('denomination_id', models.AutoField(primary_key=True, serialize=False)),
                ('denomination_name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denominations', to='admin_transaction_processing.dupayasset')),
            ],
        ),
        migrations.CreateModel(
            name='DupayAddress',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('address_name', models.CharField(max_length=255)),
                ('default_flag', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('denomination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='admin_transaction_processing.dupaydenomination')),
            ],
        ),
    ]
