# Generated by Django 5.0.7 on 2024-10-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_transaction_processing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('account_type', models.CharField(max_length=255)),
                ('account_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Dupay_Accounts',
            },
        ),
    ]
