# Generated by Django 5.0.7 on 2024-10-23 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_transaction_processing', '0002_account'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='account',
            table='admincms_accounts',
        ),
    ]
