# Generated by Django 5.0.7 on 2024-10-24 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_transaction_processing', '0005_phases'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='account_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='admin_transaction_processing.account'),
        ),
    ]
