# Generated by Django 5.0.7 on 2024-10-24 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_transaction_processing', '0006_asset_account_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Denomination',
            fields=[
                ('denomination_id', models.AutoField(primary_key=True, serialize=False)),
                ('denomination_name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='denominations', to='admin_transaction_processing.asset')),
            ],
            options={
                'db_table': 'admincms_denominations',
            },
        ),
    ]
