# Generated by Django 5.0.7 on 2024-10-25 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_transaction_processing', '0009_rename_account_id_account_duc_account_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='account_id',
            new_name='duc_account_id',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='asset_id',
            new_name='duc_asset_id',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='asset_name',
            new_name='duc_asset_name',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='created_at',
            new_name='duc_created_at',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='description',
            new_name='duc_description',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='updated_at',
            new_name='duc_updated_at',
        ),
        migrations.AlterModelTable(
            name='asset',
            table='Dupay_Assets',
        ),
    ]
