# Generated by Django 5.0.7 on 2024-10-25 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_transaction_processing', '0010_rename_account_id_asset_duc_account_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address_id',
            new_name='duc_address_id',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='address_name',
            new_name='duc_address_name',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='created_at',
            new_name='duc_created_at',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='default_flag',
            new_name='duc_default_flag',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='denomination_id',
            new_name='duc_denomination_id',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='updated_at',
            new_name='duc_updated_at',
        ),
        migrations.RenameField(
            model_name='denomination',
            old_name='asset_id',
            new_name='duc_asset_id',
        ),
        migrations.RenameField(
            model_name='denomination',
            old_name='created_at',
            new_name='duc_created_at',
        ),
        migrations.RenameField(
            model_name='denomination',
            old_name='denomination_id',
            new_name='duc_denomination_id',
        ),
        migrations.RenameField(
            model_name='denomination',
            old_name='denomination_name',
            new_name='duc_denomination_name',
        ),
        migrations.RenameField(
            model_name='denomination',
            old_name='symbol',
            new_name='duc_symbol',
        ),
        migrations.RenameField(
            model_name='denomination',
            old_name='updated_at',
            new_name='duc_updated_at',
        ),
        migrations.AlterModelTable(
            name='account',
            table='dupay_accounts',
        ),
        migrations.AlterModelTable(
            name='address',
            table='dupay_address',
        ),
        migrations.AlterModelTable(
            name='asset',
            table='dupay_assets',
        ),
        migrations.AlterModelTable(
            name='denomination',
            table='dupay_denominations',
        ),
        migrations.AlterModelTable(
            name='phases',
            table='dupay_phases',
        ),
    ]
